### ISSUE TITLE
Support Windows 64-bit platform

### ISSUE THREAD

**Issue by ceefour** [aldebaran/jnaoqi#1]
Please support Windows 64-bit platform, currently our development (https://github.com/lumenitb/avatar-nao/issues/1) is blocked due to this issue. :(

```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'naoSession' defined in class path resource [id/ac/itb/lumen/avatar/nao/NaoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.aldebaran.qimessaging.Session]: Factory method 'naoSession' threw exception; nested exception is java.lang.UnsatisfiedLinkError: C:\Users\ceefour\AppData\Local\Temp\qi.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1119)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1014)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
    at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
    at id.ac.itb.lumen.avatar.nao.NaoApplication.main(NaoApplication.java:19)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.aldebaran.qimessaging.Session]: Factory method 'naoSession' threw exception; nested exception is java.lang.UnsatisfiedLinkError: C:\Users\ceefour\AppData\Local\Temp\qi.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
    ... 15 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\ceefour\AppData\Local\Temp\qi.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at com.aldebaran.qimessaging.SharedLibrary.extractAndLoad(SharedLibrary.java:129)
    at com.aldebaran.qimessaging.SharedLibrary.loadLibHelper(SharedLibrary.java:68)
    at com.aldebaran.qimessaging.SharedLibrary.loadLib(SharedLibrary.java:30)
    at com.aldebaran.qimessaging.EmbeddedTools.loadEmbeddedLibraries(EmbeddedTools.java:110)
    at com.aldebaran.qimessaging.Session.<clinit>(Session.java:12)
    at id.ac.itb.lumen.avatar.nao.NaoConfig.naoSession(NaoConfig.java:29)
    at id.ac.itb.lumen.avatar.nao.NaoConfig$$EnhancerBySpringCGLIB$$ced98138.CGLIB$naoSession$0(<generated>)
    at id.ac.itb.lumen.avatar.nao.NaoConfig$$EnhancerBySpringCGLIB$$ced98138$$FastClassBySpringCGLIB$$4fa63946.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
    at id.ac.itb.lumen.avatar.nao.NaoConfig$$EnhancerBySpringCGLIB$$ced98138.naoSession(<generated>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
    ... 16 more
Disconnected from the target VM, address: '127.0.0.1:52499', transport: 'socket'
```

**Comment by ghostwan** [comment]
We working on it. Thank for your feedback.
